# Generated by Django 6.0.3 on 2026-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="modelo",
            field=models.CharField(default="google/gemma-2-2b-it", max_length=100),
        ),
    ]
