# Generated by Django 6.0.3 on 2026-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0002_perfilusuario_modelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversacion",
            name="favorita",
            field=models.BooleanField(default=False),
        ),
    ]
