# Generated by Django 6.0.3 on 2026-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0003_conversacion_favorita"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="tamano_fuente",
            field=models.CharField(default="normal", max_length=20),
        ),
    ]
