# Generated by Django 6.0.3 on 2026-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0004_perfilusuario_tamano_fuente"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversacion",
            name="nombre_personalizado",
            field=models.BooleanField(default=False),
        ),
    ]
