# Generated by Django 6.0.3 on 2026-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0005_conversacion_nombre_personalizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversacion",
            name="hash_publico",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
